### ISSUE TITLE
[Docs] Font color issue on the doc website

### ISSUE THREAD

**Issue by Arom1a** [radioclub/tallytime#12]
On the website [Tallytime Doc](https://tallytime.radio-club.org), when you change to light mode, the 'Github' on the top banner does not display well. 
Also, it should be GitHub but not Github!

**Comment by Arom1a** [comment]
```
.alert a {
    /* text-decoration:underline; */
}
```
In the CSS file, replace the upper part with the code below
```
.alert a {
    /* text-decoration:underline; */
    color: #fbf7f0;
}
```

**Comment by plushugh** [comment]
I will open a pull request :+1:

**Comment by plushugh** [comment]
<img width="404" alt="image" src="https://github.com/radioclub/tallytime/assets/46068081/7ea58a87-78d4-495c-ad16-7ca42a610d85">
<br>
`div#announcement` would be a better selector
inheriting the color seems fine as there is already an underline

**Comment by plushugh** [comment]
Should look like this:  
<img width="344" alt="dark theme" src="https://github.com/radioclub/tallytime/assets/46068081/e9ac14aa-cc5d-442c-8b53-3dadb9a5e74e">


<img width="325" alt="light theme" src="https://github.com/radioclub/tallytime/assets/46068081/a1b839bf-b6f5-4de5-9005-aceba4ce34b6">

**Comment by plushugh** [comment]
@Arom1a please review
