### ISSUE TITLE
[Feature Request] Add Footprints

### ISSUE THREAD

**Issue by Kelvin-Ziqi-Zhao** [radioclub/tallytime#22]
To Hardware Develop Team @Treeezheng 

## Footprint Design Information

By considering finished project 3D size and connectivity, I suggest to use SMD Module on PCB.
Some of these module do not have a completed component footprint in KiCAD, you can find their footprint information in official data sheet or szlcsc.com

Here are some useful website for footprint formate convert:
https://zhuanlan.zhihu.com/p/576608333
https://wokwi.com/tools/easyeda2kicad

### LoRa Module (E22-400T30S From EBYTE)
LCSC_ID: C2971740
Check User Manual on: [https://www.ebyte.com/downpdf.aspx?id=158](url)
You can design both footprint of 22s series and 30s&33s series, it will be usefull for later development
<img width="700" alt="image" src="https://github.com/radioclub/tallytime/assets/135286324/847b9b50-332c-4f08-b459-6a4a33b989a4">

### IPEX-4 Coaxial Connecter
LCSC_ID: C2987683
<img width="322" alt="image" src="https://github.com/radioclub/tallytime/assets/135286324/933cef48-046a-4703-b860-9e70905b2597">

### OLED 0.96-inch
May required both OLED screen (C2890596) or OLED Module (C5248080)
Screen **without** PCB converter should design the footprint of FPC solder 
<img width="350" alt="image" src="https://github.com/radioclub/tallytime/assets/135286324/c5ec2c04-f837-4d0c-880e-939f416926b7">

Screen Module **with** PCB only need design 4/5pin connecter
<img width="350" alt="image" src="https://github.com/radioclub/tallytime/assets/135286324/53c38932-4668-4c73-9d48-1897e0a1bdf6">

### Mission
Once complete the design of 
- [x] SMD LoRa Module (22dBm series)
- [x] SMD LoRa Module (30dBm and 33dBm series)
- [x] IPEX Gen4 Coaxial Connecter
- [x] ONLY OLED Screen
- [x] OLED Screen Module

Please Upload them on GitHub, I will take them into KiCAD Design, Thanks

**Comment by plushugh** [comment]
Merged:+1:
